### ISSUE TITLE
package name "public" causes mutiple problems 

### ISSUE THREAD

**Issue by rcemper** [ELynx/i2b2-on-iris#9]
No demo query uses a schema name but assume default schema.
So default schema SQLuser.* is used after docker installation for demo queries in PDF.
Setting default schema to public is possible but requires a restart of IRIS to become effective.

alternative ==> edit ALL table references to "public".<tablename>.
Quotes are required as PUBLIC is a reserved word in SQL !!
 
exception Query 5.1
select count (patient_num) as N from public.patient_dimension  where sex_cd = 'F'
this one fails too. No quotes around "public"
Change is required in PDF.

**Comment by ELynx** [comment]
Sure, this is a known issue now, and one that team will need to tackle this way or another.

`public` is used by i2b2, and we are currently looking into best solution for this.

I am sure that when we have solution ready we will also update the documentation, because now PDF is more of a compilation of what is _not_ working rather than what _is_.
